### ISSUE TITLE
Interface

### ISSUE THREAD

**Issue by entopia** [alan-turing-institute/protein_folding#15]
Create suggested interface

**Comment by jjp30** [comment]
Suggest remove 3D viewport from HumanUI window - Rhino perspective viewport works well and allows to test rendering.
Toggle for initial/final ghost structures? I couldn't locate these in GH...

**Comment by entopia** [comment]
Yes Indeed. These both will be added in the next iteration.

**Comment by entopia** [comment]
3D window removed and added separately, booleans added for switching between visualisation modes (primary-secondary structure, sidechains - Vis of data)
